In [1]:
import tensorflow as tf

In [4]:
string = tf.Variable("This is a String", tf.string)
number = tf.Variable(324, tf.int16)

In [5]:
rank1_tensor = tf.Variable(["Test"], tf.string)
rank1_tensor

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'Test'], dtype=object)>

In [6]:
rank2_tensor = tf.Variable([['test', 'ok'], ['test', 'yes']], tf.string)
rank2_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'test', b'ok'],
       [b'test', b'yes']], dtype=object)>

In [8]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [9]:
rank2_tensor.shape

TensorShape([2, 2])

In [10]:
tensor1 = tf.ones([1, 2, 3])
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [11]:
tensor2 = tf.reshape(tensor1, [2, 3, 1])
tensor2

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [12]:
tensor3 = tf.reshape(tensor2, [3, -1])
tensor3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>